# Generated by Django 5.1.1 on 2024-10-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_usermodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default-profile-img.png', null=True, upload_to='profile_images/'),
        ),
    ]
