# Generated by Django 5.1.1 on 2024-10-12 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='image',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(default='', upload_to='profile_images/'),
        ),
    ]
