# Generated by Django 5.1.1 on 2024-10-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_diary_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diary',
            old_name='content',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='image',
        ),
        migrations.AddField(
            model_name='diary',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
