# Generated by Django 5.1.1 on 2024-10-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_alter_diary_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
