# Generated by Django 5.1.1 on 2024-10-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_diary_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
