# Generated by Django 5.1.1 on 2024-10-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_comment_like_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, default='profile_imgs/profile-default-imgs-for-not-edit-person.png', null=True, upload_to='profile_imgs/'),
        ),
    ]
