# Generated by Django 5.0.7 on 2024-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0018_remove_diary_like_diary_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='share',
            field=models.BooleanField(default=True),
        ),
    ]
