# Generated by Django 5.0.7 on 2024-11-02 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0021_alter_diary_text_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
