# Generated by Django 5.0.7 on 2024-11-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0023_diary_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='pos',
        ),
        migrations.AddField(
            model_name='diary',
            name='emotion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diary',
            name='probs',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
