# Generated by Django 5.1.1 on 2024-10-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_follow_delete_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(default='', upload_to='diary_images/'),
        ),
    ]
