# Generated by Django 5.1.1 on 2024-10-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_rename_content_diary_text_remove_diary_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='images',
            field=models.ImageField(default='', upload_to='diary_images/'),
        ),
    ]
