# Generated by Django 5.1.1 on 2024-10-19 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_alter_usermodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='like',
        ),
        migrations.AddField(
            model_name='diary',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_diaries', to=settings.AUTH_USER_MODEL),
        ),
    ]
