# Generated by Django 5.0.7 on 2024-11-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0022_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='pos',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
