# Generated by Django 5.0.7 on 2024-11-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0024_remove_diary_pos_diary_emotion_diary_probs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='probs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
