# Generated by Django 5.0.7 on 2024-11-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0025_alter_diary_probs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='images',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.CharField(default='default.jpg', max_length=255),
        ),
    ]
