# Generated by Django 5.0.7 on 2024-11-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0026_remove_diary_images_alter_usermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_images/'),
        ),
    ]
